apiVersion: apps/v1
kind: Deployment
metadata:
  name: testarck8s
  namespace: default
  labels:
    app: testarck8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testarck8s
  template:
    metadata:
      labels:
        app: testarck8s
    spec:
      containers:
        - name: testarck8s
          image: mtarmidi/testarck8s  # â† tag is injected by Kustomize
          ports:
            - containerPort: 80
